### ISSUE TITLE
sql select returning query which is not runnable in mssql.

### ISSUE THREAD

**Issue by zurez-sgig** [planetarydev/json-sql-builder2#11]
`const` SQLBuilder = require('json-sql-builder2');

const sql = new `SQLBuilder('SQLServer');`
`sql.$select({
            job_title: true,
            total_salary: { $sum: 'salary' },
            $from: 'people',
            $where: {
                job_title: { $in: ['Sales Manager', 'Account Manager'] },
                age: { $gte: 18 },
                country_code: 'US',
            },
            $groupBy: 'job_title',
        })`
Converted to 

`{"sql":"SELECT job_title, SUM(salary) AS total_salary FROM people WHERE job_title IN (@param1, @param2) AND age >= @param3 AND country_code = @param4 GROUP BY job_title","values":{"param1":"Sales Manager","param2":"Account Manager","param3":18,"param4":"US"}}`

**Comment by planetarydev** [comment]
Please support an error-message that you will receive from the SQL-Server.
