### ISSUE TITLE
custom functions?

### ISSUE THREAD

**Issue by lagleki** [planetarydev/json-sql-builder2#12]
What's the easiest way to run `select to_timestamp(foo.datetime) from foo`?Is there way to pass a raw "to_timestamp(foo.datetime)" expression? Same question about `now()`

**Comment by planetarydev** [comment]
Sorry for my late answer.

Yes you have a helper called `__` to write inline-SQL like:

```javascript
result = builder.build({
  $select: {
    test: { __: 'to_timestamp(foo.datetime)' }
    $from: 'foo'
  }
};

// result is:
// SELECT to_timestamp(foo.datetime) AS test FROM foo;
```
This is a untestet snip just from my mind. Here is the link for the inline-helper [https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/__](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/__)
with some more examples.

Hope this works for you.

**Comment by planetarydev** [comment]
I've written the helpers `to_timestamp` and `now` as example to show how easy it will be to create new stuff when needed.
[https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/functions/datetime/to_timestamp](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/functions/datetime/to_timestamp)
[https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/functions/datetime/now](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/functions/datetime/now)
Please feel free to make a PR with more stuff that you will create.
Thanks!
