### ISSUE TITLE
Support for Virtual Column in Select Statement for Postgres

### ISSUE THREAD

**Issue by umer-mehmood** [planetarydev/json-sql-builder2#17]
We need to add a virtual column in select statement while composing the sql query.

Use Case:
We are trying to build a query using **postgresql** dialect. The query then will be executed on **AWS Athena Service**. And in case of **virtual columns** athena requires string values in **single qoutes** i.e. **'value' as "Column_Name**". So the issue is json-sql-builder2 does not add **single qoutes** for the value of virtual column. Let me know if there is any way. Thanks

**Comment by planetarydev** [comment]
Did you mean something like this?

```sql
SELECT 'myvalue' AS "my_column" FROM "my_table"
```

You can use the InlineSQL-helper `__` like:

```javascript
result = sql.build({
  $select: {
    my_column: { __: "'myvalue'" }
    $from: 'my_table'
  }
});
```
Please have a look at [https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/__](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/__)

**Comment by umer-mehmood** [comment]
> Did you mean something like this?
> 
> ```sql
> SELECT 'myvalue' AS "my_column" FROM "my_table"
> ```
> 
> You can use the InlineSQL-helper `__` like:
> 
> ```js
> result = sql.build({
>   $select: {
>     my_column: { __: "'myvalue'" }
>     $from: 'my_table'
>   }
> });
> ```
> 
> Please have a look at https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/__

This fulfills my requirement. Thank you!!!
