### ISSUE TITLE
Select all, with further columns?

### ISSUE THREAD

**Issue by lukesrw** [planetarydev/json-sql-builder2#20]
Is there a method for doing a select all with columns? Ideally allowing for further columns. I've looked through the documentation but I don't seem to be able to find anything referencing this,

For example:
```sql
SELECT
	Table1.*,
	Table2.Column3
FROM
	Table1
	LEFT JOIN Table2 ON Table1.Column1 = Table2.Column2
```

Hoping to be able to do:
```sql
SELECT
	Table1.*,
	(
		SELECT
			COUNT(*)
		FROM
			Table1
		WHERE
			< some conditions >
	) `count`
FROM
	Table1
WHERE
	< some conditions >
```

**Comment by planetarydev** [comment]
Please refer the docs for `select`operator  and the `join` helper.
The docs for each operator and helper always located beside the code so please browse through the /sql directory and you will find tons :-) of tests and examples.

[/sql/operators/select](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/operators/select)
[/sql/helpers/queries/join](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/queries/join)

It is possible out of the box like the example below:

```javascript
result = sql.$select({
  'Table1.*': true,
  't2.column1': true,
  't2.column2': true,
  count: { $select: { c: { $count: '*' }, $from: 'Table1', $where: { col1: 'Test' } } },
  $from: 'Table1',
  $join: {
    t2: {
      $leftJoin: {
        $table: 'Table2',
        $on: { 'table1.id': '~~t2.id' }
      }
    }
  }
});
```

Did this fit your needs?
