### ISSUE TITLE
Division arithmetic helper does not exists

### ISSUE THREAD

**Issue by umer-mehmood** [planetarydev/json-sql-builder2#23]
Hello, we have a use case, in which we have to divide a column with an integer value. To do that I am not able to find any arithmetic helper. There exists two for **addition** and **multiplication**, but we also have to apply division operation on a column. 

**Example:** Select * from column1 * 1, column2 / 2 from Table

Kindly let me know if there is any way to achieve this. Thanks

**Comment by planetarydev** [comment]
Yes, if you want you can contribute and add a `$div` helper by yourself. 
As template you could easily use the `$mul` helper. After adding the div directory, adding the source-file div.js with tests please run `npm test` and the readme will be generated automatcally after a successful test-run.

Here is the location of the mul helper:
[https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/arithmetic/mul](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/arithmetic/mul)

**Comment by planetarydev** [comment]
sorry, I dont want to close :-) ... hm, reopend again ...
If you got further questions please let me know

**Comment by umer-mehmood** [comment]
Hello, I have implemented the $div helper and tested it. The documentation
file is also added along with the readme file.

Kindly can you give access of the repository, so that i can push the
feature branch and create a pull request for master branch.

Regards,

Umer Mehmood

NorthBay

Direct: +92 3234971359

umer.mahmood@northbaysolutions.net <faheem.khan@northbaysolutions.net>

www.Northbaysolutions.com <http://www.northbaysolutions.com/>

**Comment by planetarydev** [comment]
You dont need access to the original repo. You can fork it and with the help of the fork you can make your PR. Here is how to do that [Create PR from a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Thanks in advance and awaitig your PR.

**Comment by umer-mehmood** [comment]
Hello, I have forked and generated a PR regarding that $div helper.

Kindly look into it and let me know if there are any changes.

Regards,

Umer Mehmood

NorthBay

Direct: +92 3234971359

umer.mahmood@northbaysolutions.net <faheem.khan@northbaysolutions.net>

www.Northbaysolutions.com <http://www.northbaysolutions.com/>

**Comment by planetarydev** [comment]
done with PR #24
