### ISSUE TITLE
Using cast function in WHERE clause

### ISSUE THREAD

**Issue by planetarydev** [planetarydev/json-sql-builder2#26]
i want to cast any column type while using it in
where.

E.g.
Select * from table1
Where cast(date) = '2019-09-01'

**Comment by planetarydev** [comment]
@umer-mehmood You can use the `$anyExpr` helper or the short-hand simply `$`.
But you need th write the cast helper at first.

```javascript
sql.build({
  $select: {
    $from: 'people',
    $where: {
      $and: [
        { $: { $cast: '~~my_date_column', $eq: 10 } }
      ]
    }
  }
});
```

I though it was not so intuitiv. baut it works. Did you have any idea to implement some other logic for this?

**Comment by umer-mehmood** [comment]
Yes, I have added a CAST helper and using the **$anyExpr / $** operator i am able to use a function in where clause.

**Comment by planetarydev** [comment]
Thanks!
