### ISSUE TITLE
isValidIdent method question

### ISSUE THREAD

**Issue by rojoyin** [planetarydev/json-sql-builder2#29]
Hello,

I am sending this json
```json
{
    "$select": {
        "$columns": ["day", "firstname", "lastname"],
        "$from": "a.b.1"
    }
}
```
As a result I got:
```json
{
  "sql": "SELECT day, firstname, lastname FROM a.b.\"1\"",
  "values": []
}
```

What I was expecting was:
```json
{
  "sql": "SELECT day, firstname, lastname FROM a.b.1",
  "values": []
}
```
The point in the code that changes what I expected is in the following validation.
https://github.com/planetarydev/json-sql-builder2/blob/d0944e64bf25b7b54d05f097a84567b9a22fd2da/lib/builder.js#L129-L131

Is there any reason the identifier must not begin with numbers?

I could fix it, if there is no problem in changing this condition.

Best regards.

**Comment by planetarydev** [comment]
My major System is postgres and there it is Not allowed. You can fix it in condition to the specific System you need. Or a netter way is to implement an option for that.

**Comment by rojoyin** [comment]
I solved by using the function setQuoteChar passing the parameter with value ''
Thank you
