### ISSUE TITLE
no such file or directory, scandir '/sql/'  issue  var sql = new SQLBuilder('SQLServer');  

### ISSUE THREAD

**Issue by dhaneshhs** [planetarydev/json-sql-builder2#9]
I'm getting this below error on deploying aws lambda node 8.10.0

2019-05-09T04:23:22.996Z	6010d98c-2788-4c96-b972-49361876948c	Error: ENOENT: no such file or directory, scandir '/sql/'
at Object.fs.readdirSync (fs.js:904:18)
at Object.walk (/var/task/src/index.js:144899:16)
at SQLBuilder._loadModules (/var/task/src/index.js:144709:23)
at new SQLBuilder (/var/task/src/index.js:144298:8)
at handler (/var/task/src/index.js:76189:15)

**Comment by planetarydev** [comment]
Im not familiar with aws lambda, but it seems that SQLBuilder got problems loading the operator- and helper-modules located in /sql.
Some Background: SQLBuilder dynamically walks recursive through the /sql directory and loads all js-files located there. Each file represents an operator or helper like "select.js" or "from.js", etc.

Could you spend some time to analyse this. Maybe this would be some similar error with lamda [https://stackoverflow.com/questions/49020710/lambda-enoent-no-such-file-or-directory](https://stackoverflow.com/questions/49020710/lambda-enoent-no-such-file-or-directory)

Hope this would help

Some more question: Does it work locally?

**Comment by dhaneshhs** [comment]
@planetarydev  yes it worked locally in windows system. we are using webpack it is creating the single index.js file. but these files inside /sql are not getting added to the deployment package.
sql
src
src/index.js
i made my deployment package look like this then also it is not able to find the folder
[image](https://user-images.githubusercontent.com/14539950/57435391-e9676000-725a-11e9-95a6-67934893d709.png)

**Comment by dhaneshhs** [comment]
Below warning will be displayed when Bundling with webpack.


WARNING in ./node_modules/json-sql-builder2/lib/operator.js
103:19-38 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/json-sql-builder2/lib/operator.js
 @ ./node_modules/json-sql-builder2/lib/builder.js
 @ ./node_modules/json-sql-builder2/index.js
 @ ./src/index.ts

WARNING in ./node_modules/json-sql-builder2/lib/builder.js
474:18-31 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/json-sql-builder2/lib/builder.js
 @ ./node_modules/json-sql-builder2/index.js
 @ ./src/index.ts

WARNING in ./node_modules/json-sql-builder2/lib/builder.js
551:19-42 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/json-sql-builder2/lib/builder.js
 @ ./node_modules/json-sql-builder2/index.js
 @ ./src/index.ts

WARNING in ./node_modules/json-sql-builder2/lib/builder.js
568:17-40 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/json-sql-builder2/lib/builder.js
 @ ./node_modules/json-sql-builder2/index.js
 @ ./src/index.ts

**Comment by planetarydev** [comment]
I think that it would not work with webpack because the require of all node-modules for operators and helpers will work dynamically by walking through the directories.

```javascript
        /****
	 * Register all Modules located in the /sql directory.
	 *
	 * All Files located in a directory named "helpers" will
	 * registered as Helper. All files located in "operators" will
	 * resgistered as Operator. Directories which named "private" will be skipped.
	 *
	 */
	_loadModules(){
		let modules = tools.walk(path.join(__dirname, `../sql/`));

		_.forEach(modules, (module) => {
			if (module.endsWith('.js') && module.indexOf('private') == -1 && !path.basename(module).startsWith('.')) {
				this._register(module);
			}
		});
	}

	/**
	 * @summary Creates a new Operator or Helper
	 *
	 * @param file 	{String}	Specifies the path and filename of the operator or helper to register
	 */
	_register(file) {
		let sqlModule = require(file);
``
